### ISSUE TITLE
Feedback zur Klasse Finanzamt

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group11-exercise3#1]
## Klasse `Finanzamt`

  * Variablenname `NAME` verstößt gegen die Coding-Convention, korrekt wäre `name`
  * Für die Deklaration von Variablen und Rückgabetypen in Zusammenhang mit Collections verwendet man das Interface und nicht die Klasse, also z.B. in Zeile 13: `List<Besteuerbar> steuerzahler = new ArrayList< Besteuerbar>()` anstatt  `ArrayList<Besteuerbar> steuerzahler = new ArrayList< Besteuerbar>()`. Analog für die `getSteuerzahler()`-Methode.
  * Berechnung der Steuer fehlt in der `steuerAuslesen()`-Methode
  * Die Steuer hier zu berechnen hat den Nachteil, dass man die Instanceof-Kette für neue Klassen erweitern muss und verstößt so gegen das _Open-Closed-Prinzip_. Besser wäre die Steuerberechnung in die verschiedenen Klassen, wie `Schurke` und `Syndikat` zu verlegen.

**Comment by wagnst** [comment]
- Danke für die Info bzgl. der Collections. Dies war mir bisher nicht klar
- SteuerAuslesen konnte zeitbedingt leider nicht mehr umgesetzt werden (daher das "Gemurkse" mit instanceof ;-))
