### ISSUE TITLE
Feedback zur Klasse ProgressiveSteuer

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group11-exercise3#2]
## Klasse ProgressiveSteuer

Die Steuerberechnung ist wahrscheinlich falsch. Die Steuer der nächste Stufe wird nur auf den Betrag erhoben, der dir vorhergehende Stufe übersteigt. Also müsste in jedem if der Betrag verringert werden.

Hinzu kommt noch, dass die Beträge und Steuern nicht als Konstanten, sondern als magische Werte ausgewiesen sind.

**Comment by wagnst** [comment]
- Vermutlich würde sie nicht korrekt funktionieren, da ich sie in den letzten 2 Minuten hingehackt habe... Leider auch aus zeitlichen Gründen nicht "korrekter" machbar gewesen.
- Das Prinzip hatte ich dann schon verstanden, war aber (wie gesagt) in der Zeit leider doch nicht umsetzbar.. :-(
