### ISSUE TITLE
Feedback zum UML-Diagramm

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group11-exercise3#4]
## UML-Diagramm

  * VIsio scheint nicht das Tool der Wahl zu sein ;-)
  * `RichterKorrupt` ist als Klasse unnötig, da alle Richter entweder korrupt sind oder nicht
  * Aggregationsbeziehungen zwischen Personengesellschaft bzw. Kapitalgesellschaft und Bürger/Syndikat und Schurke fehlen
  * Die Implementierungspfeile sind verkehrt herum

**Comment by wagnst** [comment]
Für die schnelle (OOT) war Visio ausreichend. Leider wurden Tools in OOT viel zu wenig behandelt... da hätte ich mir mehr gewünscht.
Haben Sie Tools die SIe für die Modellierung empfehlen? Folgende Features wären interessant:
* Generierung Klassendiagramm aus Quell-Code heraus
* Modellierung Klassendiagramm und Klassen / Paketgenerierung aus Diagramm
* Alle UML Standards abgebildet
* "additional" ER-Diagramme (für DB2) :+1:

**Comment by thomsmits** [comment]
Hallo,

UML-Tools sind nicht meine Spezialität. Ich habe die Erfahrung gemacht, dass alle Tools mehr oder weniger nervig sind. Je mehr "Automatik" eingebaut sind, desto mehr Gefummel hat man damit. Insofern male ich meine UML-Diagramme tatsächlich mit einem einfachen Vektor-Grafikprogramm (OmniGraffle). Sorry, also kein Tipp von mir an dieser Stelle.

Mit freundlichen Grüßen

  Thomas Smits
