### ISSUE TITLE
Bewertung des Testates vom 07.05.2015

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group11-exercise3#5]
# Bewertung

## UML-Diagramm

Das UML-Diagramm ist weitgehend in Ordnung, enthält aber einige kleinere Schwächen.

**45 Punkte**

## Ergebnis des Live-Testates

Das Ergebnis des Live-Testates ist weitgehend in Ordnung, es fehlt allerdings die Steuerberechnung. Bis auf kleinere Schwächen ist die Implementierung aber angemessen und das UML-Diagramm wird umgesetzt.

**40 Punkte**

## Gesamtpunktzahl für das Übungsblatt

**85 Punkte**

**Comment by wagnst** [comment]
Die Zeit war für das Programm wie wir es modelliert haben leider zu knapp bemessen; daher leider auch an einigen Stellen lückenhaft.
Mit dem Ergebnis aber sind wir sehr zufrieden! Danke für das ausführliche Feedback!
